# Generated by Django 6.0.7 on 2026-07-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilnutricionista_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilnutricionista',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='perfilnutricionista',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC'),
        ),
    ]
