# Generated by Django 6.0.6 on 2026-07-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_consulta_archivopaciente_consulta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planalimentario',
            options={'ordering': ['-fecha_creacion', '-version'], 'verbose_name': 'Plan Alimentario Sync', 'verbose_name_plural': 'Planes Alimentarios Sync'},
        ),
        migrations.AddField(
            model_name='planalimentario',
            name='plan_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_posteriores', to='pacientes.planalimentario', verbose_name='Plan anterior/origen'),
        ),
        migrations.AddField(
            model_name='planalimentario',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
    ]
