# Generated by Django 6.0.7 on 2026-07-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0016_alter_planalimentario_options_and_more'),
        ('pacientes', '0016_merge_20260711_1601'),
    ]

    operations = [
    ]
