# Generated by Django 6.0.7 on 2026-07-12 02:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0006_alter_cita_estado'),
        ('pacientes', '0016_alter_planalimentario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del plan')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio mensual (S/)')),
                ('precio_anual', models.DecimalField(decimal_places=2, help_text='Precio con descuento por facturación anual', max_digits=8, verbose_name='Precio anual (S/)')),
                ('limite_pacientes', models.PositiveIntegerField(default=-1, help_text='Número máximo de pacientes (-1 = ilimitado)', verbose_name='Límite de pacientes')),
                ('limite_citas_mes', models.PositiveIntegerField(default=-1, help_text='Número máximo de citas al mes (-1 = ilimitado)', verbose_name='Límite de citas por mes')),
                ('comision_cobros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión sobre cada cobro a pacientes', max_digits=5, verbose_name='Comisión sobre cobros (%)')),
                ('comision_suscripcion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje adicional sobre el cobro de la suscripción', max_digits=5, verbose_name='Comisión sobre suscripción (%)')),
                ('stripe_price_id_mensual', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID (Mensual)')),
                ('stripe_price_id_anual', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID (Anual)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('consulta', 'Consulta'), ('plan_alimentario', 'Plan Alimentario'), ('seguimiento', 'Seguimiento'), ('paquete', 'Paquete'), ('otro', 'Otro')], default='consulta', max_length=30, verbose_name='Concepto')),
                ('descripcion', models.TextField(help_text='Detalle del servicio facturado', verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto (S/)')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total (S/)')),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Comisión plataforma (S/)')),
                ('monto_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Monto neto (S/)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('metodo_pago_usado', models.CharField(blank=True, choices=[('stripe', 'Tarjeta (Stripe)'), ('yape', 'Yape'), ('plin', 'Plin'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de pago utilizado')),
                ('referencia_pago', models.CharField(blank=True, help_text='Código de transacción o referencia del pago', max_length=200, verbose_name='Referencia de pago')),
                ('comprobante_pago', models.FileField(blank=True, help_text='Captura o comprobante del pago realizado', upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante de pago')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Payment Intent ID')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='citas.cita', verbose_name='Cita asociada')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal (S/)')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IGV 18% (S/)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total (S/)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('archivo_pdf', models.FileField(blank=True, upload_to='facturas/%Y/%m/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario (S/)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Subtotal (S/)')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_factura', to='facturacion.cobro', verbose_name='Cobro asociado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto (S/)')),
                ('metodo_pago', models.CharField(choices=[('stripe', 'Tarjeta (Stripe)'), ('yape', 'Yape'), ('plin', 'Plin'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Método de pago')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Charge ID')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('comprobante', models.FileField(blank=True, upload_to='comprobantes_pago/%Y/%m/', verbose_name='Comprobante')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('comision_stripe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Comisión Stripe (S/)')),
                ('monto_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Monto neto recibido (S/)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturacion.cobro', verbose_name='Cobro')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='facturacion.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionNutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_facturacion', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10, verbose_name='Tipo de facturación')),
                ('precio_aplicado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio aplicado (S/)')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('pendiente_pago', 'Pendiente de pago')], default='pendiente_pago', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Customer ID')),
                ('renovacion_automatica', models.BooleanField(default=True, verbose_name='Renovación automática')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('nutricionista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.plansuscripcion', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='facturacion_estado_3588bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['paciente', 'estado'], name='facturacion_pacient_ae2118_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturacion_numero__d0f299_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado', 'fecha_emision'], name='facturacion_estado_008ea8_idx'),
        ),
    ]
