# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0002_datos_iniciales_planes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plansuscripcion",
            name="limite_pacientes",
            field=models.IntegerField(
                default=-1,
                help_text="Número máximo de pacientes (-1 = ilimitado)",
                verbose_name="Límite de pacientes",
            ),
        ),
        migrations.AlterField(
            model_name="plansuscripcion",
            name="limite_citas_mes",
            field=models.IntegerField(
                default=-1,
                help_text="Número máximo de citas al mes (-1 = ilimitado)",
                verbose_name="Límite de citas por mes",
            ),
        ),
    ]
