# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facturacion", "0004_completar_planes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="nutricionista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_facturacion",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nutricionista",
            ),
        ),
    ]
