# Generated by Django 6.0.6 on 2026-07-11 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_receta_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comidaplan',
            options={'ordering': ['hora_sugerida', 'id'], 'verbose_name': 'Comida del plan', 'verbose_name_plural': 'Comidas del plan'},
        ),
        migrations.AlterModelOptions(
            name='plannutricional',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Modelo de Plan', 'verbose_name_plural': 'Modelos de Planes'},
        ),
        migrations.RemoveIndex(
            model_name='plannutricional',
            name='nutricion_p_pacient_fef806_idx',
        ),
        migrations.RemoveIndex(
            model_name='plannutricional',
            name='nutricion_p_fecha_i_63defb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='comidaplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comidaplan',
            name='hora_sugerida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario sugerido'),
        ),
        migrations.AddField(
            model_name='comidaplan',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones sugeridas'),
        ),
        migrations.AddField(
            model_name='comidaplan',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comidas_plan', to='nutricion.receta', verbose_name='Receta seleccionada'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='agua_recomendada',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3, verbose_name='Agua recomendada (L)'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción del propósito de este modelo de plan', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='fibra_g',
            field=models.PositiveIntegerField(default=25, verbose_name='Fibra (g)'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='num_comidas',
            field=models.PositiveIntegerField(default=4, verbose_name='Número de comidas'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_planes', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista'),
        ),
        migrations.AddField(
            model_name='plannutricional',
            name='tipo_paciente',
            field=models.CharField(default='General', help_text='Ej: Adulto activo, Deportista, Sedentario', max_length=100, verbose_name='Tipo de paciente'),
        ),
        migrations.AlterField(
            model_name='comidaplan',
            name='tipo_comida',
            field=models.CharField(help_text='Ej: Desayuno, Merienda, Cena', max_length=50, verbose_name='Nombre de la comida'),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Activo', 'Activo'), ('Archivado', 'Archivado')], default='Borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plannutricional',
            name='nombre',
            field=models.CharField(help_text='Ej: Plan hiperproteico de definición', max_length=200, verbose_name='Nombre del plan'),
        ),
        migrations.AddIndex(
            model_name='plannutricional',
            index=models.Index(fields=['nutricionista', 'estado'], name='nutricion_p_nutrici_e94677_idx'),
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='comidaplan',
            name='alimentos_sugeridos',
        ),
        migrations.RemoveField(
            model_name='comidaplan',
            name='calorias_estimadas',
        ),
        migrations.RemoveField(
            model_name='comidaplan',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comidaplan',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='comidaplan',
            name='recetas_sugeridas',
        ),
    ]
