# Generated by Django 6.0.5 on 2026-05-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.TextField(help_text='Breve descripción del motivo de la cita', verbose_name='Motivo de la consulta'),
        ),
    ]
