# Generated by Django 6.0.5 on 2026-05-23 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de la consulta'),
        ),
    ]
