# Generated by Django 6.0.5 on 2026-05-23 00:42

import citas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[citas.validators.validate_costo_positivo], verbose_name='Costo de la consulta'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=45, help_text='Duración estimada de la consulta en minutos', validators=[citas.validators.validate_duracion_minutos], verbose_name='Duración (minutos)'),
        ),
    ]
