# Generated by Django 6.0.6 on 2026-07-10 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_costo_alter_cita_duracion_minutos'),
        ('pacientes', '0014_archivopaciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió'), ('bloqueada', 'Bloqueada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('primera_consulta', 'Primera Consulta'), ('seguimiento', 'Seguimiento'), ('control', 'Control'), ('evaluacion', 'Evaluación'), ('bloqueo', 'Bloqueo de Horario')], default='seguimiento', max_length=20, verbose_name='Tipo de consulta'),
        ),
    ]
