# Generated by Django 6.0.6 on 2026-07-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_nutricionista_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('en_consulta', 'En consulta'), ('finalizada', 'Finalizada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió'), ('bloqueada', 'Bloqueada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
    ]
