# Generated by Django 6.0.7 on 2026-07-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_merge_20260711_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaclinica',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('seguimiento', 'Seguimiento'), ('observacion', 'Observación')], default='consulta', max_length=20, verbose_name='Tipo'),
        ),
    ]
